apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: kubernetes-prometheus
profiles:
  - name: local
    deploy:
      kubectl:
        manifests:
          - minikube-deploy/env-local.yaml
          - minikube-deploy/nfs-mainfest.yaml
          - minikube-deploy/mysql-mainfest.yaml
          - eks-deploy/jupyterhub-mainfest.yaml
