apiVersion: v1
kind: PersistentVolume # Create PV
metadata:
  name: pv-nfs # Sets PV name
  labels:
    type: local # Sets PV's type
    app: nfs
spec:
  #storageClassName: manual
  claimRef:
    name: nfs-pvc-claim
  capacity:
    storage: 3Gi # Sets PV's size
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/nfs # Sets PV's host path

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-claim
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: manual
  resources:
    requests:
      storage: 3Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs
  template:
    metadata:
      labels:
        app: nfs
    spec:
      containers:
        - image: "gcr.io/google_containers/volume-nfs:0.8"
          name: nfs-server
          ports:
            - containerPort: 2049
              name: nfs
            - containerPort: 20048
              name: mountd
            - containerPort: 111
              name: rpcbind
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /exports
              name: nfs-pvc
      volumes:
        - name: nfs-pvc
          persistentVolumeClaim:
            claimName: nfs-pvc-claim
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-service
  labels:
    app: nfs
spec:
  selector:
    app: nfs
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
