apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster-in-vpc
  region: us-east-1
  version: '1.17'

vpc:
  id: vpc-12345
  cidr: "10.0.0.0/16"
  subnets:
     public:
       us-east-1a:
         id: subnet-0ff156e0c4a6d300c
       us-east-1b:
         id: subnet-0549cdab573695c03
    
nodeGroups:
  - name: ng-medium-mtype
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 0
    maxSize: 10
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
